### ISSUE TITLE
feat: Should add OAuth 2.0 handler to allow other workspaces install the slack app

### ISSUE THREAD

**Issue by LemonNekoGH** [nekomeowww/insights-bot#37]
Reference: [Slack Docs](https://api.slack.com/authentication/oauth-v2)
**TODO List:**
- [x] Add HTTP handler to receive temporary access code, and request for pernament access token, then save it to database
- [x] Refactor smr command handler, use team id to query access token, then send it to smr processor
- [x] Refactor smr processor, use received access token to send process result
